ablator/ablator/urls.py
from django.conf.urls import url, include

# from django.contrib import admin

urlpatterns = [
    url(r"^api/", include("api.urls")),
    url(r"^management/", include("user_management.urls")),
    url(r"^logging/", include("request_logging.urls")),
    url(r"^", include("web_admin.urls")),
]

ablator/api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

# flake8: noqa


# v1 API
urlpatternsV1 = [
    url(r"^v1/caniuse/(?P<client_user_string>[^/]+)/(?P<functionality_id>[^/]+)/?$", views.CanIUseSingleViewV1.as_view()),
    url(r"^v1/which/(?P<client_user_string>[^/]+)/(?P<functionality_id>[^/]+)/?$", views.WhichSingleViewV1.as_view()),
]

# v2 API
urlpatternsV2 = [
    url(r"^v2/which/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/?$", views.WhichViewV2.as_view()),
    url(r"^v2/caniuse/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/?$", views.CanIUseViewV2.as_view()),
]

# v3 API
urlpatternsV3 = [
    url(r"^v3/(?P<organization_id>[^/]+)/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/caniuse/?$", views.CanIUseViewV2.as_view()),
    url(r"^v3/(?P<organization_id>[^/]+)/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/flavors/?$", views.WhichViewV2.as_view()),
    url(r"^v3/(?P<organization_id>[^/]+)/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/tag/?$", views.TagListViewV3.as_view()),
    url(
        r"^v3/(?P<organization_id>[^/]+)/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/tag/(?P<tag_name>[^/]+)/remove/?$",
        views.TagRemoveViewV3.as_view(),
    ),
]

# v4 API
urlpatternsV4 = [
    url(r"^v4/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/caniuse/?$", views.CanIUseViewV4.as_view()),
    url(r"^v4/(?P<organization_id>[^/]+)/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/flavors/?$", views.WhichViewV2.as_view()),
    url(r"^v4/(?P<organization_id>[^/]+)/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/tag/?$", views.TagListViewV3.as_view()),
    url(
        r"^v4/(?P<organization_id>[^/]+)/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/tag/(?P<tag_name>[^/]+)/remove/?$",
        views.TagRemoveViewV3.as_view(),
    ),
    url(r"^v4/(?P<client_user_string>[^/]+)/(?P<app_id>[^/]+)/signals/(?P<signal_name>[^/]+)/?$", views.PostSignalViewV4.as_view()),
]

# Complete API
urlpatterns = format_suffix_patterns(urlpatternsV1 + urlpatternsV2 + urlpatternsV3 + urlpatternsV4)

ablator/web_admin/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from .views import app, functionality, index, flavor, rolloutstrategy, availability, tagging, telemetry
from django.contrib.auth import views as auth_views

# flake8: noqa: E501

urlpatterns = [
    # Account
    url(r"accounts/login/$", auth_views.LoginView.as_view(), name="login"),
    url(r"accounts/logout/$", auth_views.LogoutView.as_view(), name="logout"),
    # App
    url(r"app/create/$", app.AppCreate.as_view(), name="app-create"),
    url(r"app/(?P<app_id>[^/]+)/$", app.AppDetail.as_view(), name="app-detail"),
    url(r"app/(?P<app_id>[^/]+)/usage/$", app.AppUsage.as_view(), name="app-usage"),
    url(r"app/(?P<pk>[^/]+)/update/$", app.AppUpdate.as_view(), name="app-update"),
    url(r"app/(?P<pk>[^/]+)/delete/$", app.AppDelete.as_view(), name="app-delete"),
    # Telemetry
    url(r"app/(?P<app_id>[^/]+)/telemetry/$", telemetry.SignalListView.as_view(), name="telemetry-signal-list"),
    # Functionality
    url(r"app/(?P<pk>[^/]+)/add_functionality/$", functionality.FunctionalityCreate.as_view(), name="functionality-create"),
    url(r"functionality/(?P<pk>[^/]+)/$", functionality.FunctionalityDetail.as_view(), name="functionality-detail"),
    url(r"functionality/(?P<pk>[^/]+)/update/$", functionality.FunctionalityUpdate.as_view(), name="functionality-update"),
    url(r"functionality/(?P<pk>[^/]+)/delete/$", functionality.FunctionalityDelete.as_view(), name="functionality-delete"),
    url(r"functionality/(?P<pk>[^/]+)/flavors/$", functionality.FunctionalityFlavors.as_view(), name="functionality-flavors"),
    url(r"functionality/(?P<pk>[^/]+)/rollouts/$", functionality.FunctionalityRollouts.as_view(), name="functionality-rollouts"),
    url(r"functionality/(?P<pk>[^/]+)/logs/$", functionality.FunctionalityLogs.as_view(), name="functionality-logs"),
    # Functionality Partials
    url(
        r"functionality/enabled-users/(?P<pk>[^/]+)/$",
        functionality.FunctionalityPartEnabledUsers.as_view(),
        name="functionality-part-enabled-users",
    ),
    url(r"functionality/progress/(?P<pk>[^/]+)/$", functionality.FunctionalityPartProgress.as_view(), name="functionality-part-progress"),
    url(r"functionality/flavors/(?P<pk>[^/]+)/$", functionality.FunctionalityPartFlavors.as_view(), name="functionality-part-flavors"),
    # Flavor
    url(r"functionality/(?P<pk>[^/]+)/add_flavor/$", flavor.FlavorCreate.as_view(), name="flavor-create"),
    url(r"flavor/(?P<pk>[^/]+)/update/$", flavor.FlavorUpdate.as_view(), name="flavor-update"),
    url(r"flavor/(?P<pk>[^/]+)/delete/$", flavor.FlavorDelete.as_view(), name="flavor-delete"),
    # Rollout Strategy
    url(
        r"functionality/(?P<pk>[^/]+)/add_rolloutstrategy/$",
        rolloutstrategy.RolloutStrategyCreate.as_view(),
        name="rollout-strategy-create",
    ),
    url(r"rolloutstrategy/(?P<pk>[^/]+)/update/$", rolloutstrategy.RolloutStrategyUpdate.as_view(), name="rollout-strategy-update"),
    url(r"rolloutstrategy/(?P<pk>[^/]+)/delete/$", rolloutstrategy.RolloutStrategyDelete.as_view(), name="rollout-strategy-delete"),
    # Home Page
    url(r"^$", index.HomePageView.as_view(), name="home"),
    url(r"^status/?$", index.StatusView.as_view(), name="status"),
    # User Profiling
    url(r"availability/$", availability.AvailabilitySearch.as_view(), name="availability-index"),
    url(r"availability/(?P<user>[^/]+)/$", availability.AvailabilityList.as_view(), name="availability-list"),
    url(r"availability/(?P<user>[^/]+)/(?P<pk>[^/]+)/update/$", availability.AvailabilityUpdate.as_view(), name="availability-update"),
    url(r"availability/(?P<user>[^/]+)/(?P<pk>[^/]+)/delete/$", availability.AvailabilityDelete.as_view(), name="availability-delete"),
    # Tags
    url(r"tags/$", tagging.TagsListView.as_view(), name="tags-list"),
    url(r"tags/create/$", tagging.TagCreateView.as_view(), name="tags-create"),
    url(r"tags/(?P<pk>[^/]+)/$", tagging.TagDetailView.as_view(), name="tags-detail"),
    url(r"tags/(?P<pk>[^/]+)/update/$", tagging.TagUpdateView.as_view(), name="tags-update"),
    url(r"tags/(?P<pk>[^/]+)/delete/$", tagging.TagDeleteView.as_view(), name="tags-delete"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

ablator/core/models.py
import hashlib
import uuid

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.urls.base import reverse_lazy
from django.utils import timezone

from core.colors import random_color
from user_management.models import Organization


class ClientUser(models.Model):
    """
    A user of the software.

    Users are always anonymized and only represented by a hash
    value, so privacy can be guaranteed.

    Hashing will use the provided object's __repr__ method, so please
    make sure that the __repr__ method outputs a value that is unique to
    the user and unchanging.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    nickname = models.CharField(max_length=255, blank=True, null=True)

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name

    @property
    def short_name(self):
        if self.nickname is None:
            return self.name[:8]
        return self.name[:8] + " " + self.nickname

    @classmethod
    def user_from_object(cls, user_object, organization: Organization = None, organization_id: str = None):
        if organization:
            user_hash = cls.hash_from_object(user_object, str(organization.id))
        elif organization_id:
            user_hash = cls.hash_from_object(user_object, organization_id)
        else:
            raise AttributeError("You need to specify an Organization")
        instance, created = cls.objects.get_or_create(name=user_hash)
        return instance

    @classmethod
    def hash_from_object(cls, hashable_object, organization_id: str):
        string_to_hash = str(hashable_object) + str(organization_id)
        return hashlib.sha256(settings.HASH_SALT.encode() + string_to_hash.encode()).hexdigest()


class App(models.Model):
    """
    A collection of FunctionalityGroups.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=140)
    slug = models.SlugField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)

    def __str__(self):
        return "{}.{}".format(self.organization, self.slug)

    def get_absolute_url(self):
        return reverse_lazy("app-detail", kwargs={"app_id": self.id})


class Functionality(models.Model):
    """
    A behaviour, functionality, or program option to be managed.

    A Functionality contains one or more Flavor objects that represent individual
    variations of one functionality. This is helpful when you want to A/B test multiple
    incarnations of a functionality.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=140)
    slug = models.SlugField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    app = models.ForeignKey(App, on_delete=models.CASCADE)

    def __str__(self):
        return "{}.{}".format(self.app, self.slug)

    class Meta:
        verbose_name_plural = "Functionalities"

    @property
    def slug_as_scorecase(self):
        return self.slug.replace("-", "_")

    @property
    def number_of_users(self):
        return Availability.objects.filter(flavor__functionality=self).count()

    @property
    def number_of_enabled_users(self):
        return Availability.objects.filter(flavor__functionality=self, is_enabled=True).count()

    def get_absolute_url(self):
        return reverse_lazy("functionality-detail", kwargs={"pk": self.id})

    def get_default_tag(self):
        from tagging.models import Tag

        return Tag.objects.get_or_create(name="Default", organization=self.app.organization)[0]


class Flavor(models.Model):
    """
    A specific version of a functionality.

    Add more then one Flavor to a Functionality to A/B test. One will be randomly
    activated depending on its enable_probability.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=140)
    slug = models.SlugField(max_length=100)
    functionality = models.ForeignKey(Functionality, on_delete=models.CASCADE)
    client_users = models.ManyToManyField(ClientUser, through="Availability")
    color = models.CharField(max_length=6, default=random_color)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}.{}".format(self.functionality, self.slug)

    @property
    def number_of_users(self):
        return self.availability_set.count()

    @property
    def number_of_enabled_users(self):
        return self.availability_set.filter(is_enabled=True).count()

    @property
    def number_of_disabled_users(self):
        return self.availability_set.filter(is_enabled=False).count()

    @property
    def single_width_percent(self):
        try:
            return float(self.number_of_enabled_users) / self.number_of_users * 100
        except ZeroDivisionError:
            return 1 * 100

    @property
    def width_percent(self):
        try:
            return float(self.number_of_enabled_users) / self.functionality.number_of_users * 100
        except ZeroDivisionError:
            return 1 * 100

    def get_absolute_url(self):
        return reverse_lazy("functionality-detail", kwargs={"pk": self.functionality.id})


class RolloutStrategy(models.Model):
    """
    A description of how a feature should be rolled out, depending on a tag.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    functionality = models.ForeignKey(Functionality, on_delete=models.CASCADE)
    possible_flavors = models.ManyToManyField(Flavor, blank=False)
    tag = models.ForeignKey("tagging.Tag", on_delete=models.CASCADE, null=True, blank=True)

    start_at = models.DateTimeField(default=timezone.now)
    max_enabled_users = models.IntegerField(default=0)
    priority = models.PositiveSmallIntegerField(default=0)

    RECALL_FUNCTIONALITY = "recall"
    PAUSE_ROLLOUT = "pause_rollout"
    DEFINED_BY_RELEASES = "defined_by_releases"
    ENABLE_GLOBALLY = "enable_globally"
    STRATEGY_CHOICES = (
        (RECALL_FUNCTIONALITY, "Recall"),
        (PAUSE_ROLLOUT, "Roll Out Paused"),
        (DEFINED_BY_RELEASES, "Release-Driven"),
        (ENABLE_GLOBALLY, "Enabled Globally"),
    )
    strategy = models.CharField(max_length=50, choices=STRATEGY_CHOICES, default=DEFINED_BY_RELEASES)

    class Meta:
        ordering = ["start_at"]
        unique_together = ("tag", "functionality")

    def get_absolute_url(self):
        return reverse_lazy("functionality-detail", kwargs={"pk": self.functionality.id})

    def clean(self):
        super().clean()

        # make sure only the functionality's flavors are selected
        for flavor in self.possible_flavors.all():
            if flavor.functionality != self.functionality:
                raise ValidationError({"possible_flavors": "Only Related Flavors can be selected"})

        # make sure only the organization's tags are selected
        if self.tag and self.functionality and self.tag.organization != self.functionality.app.organization:
            raise ValidationError({"tag": "Only your organization's tags can be selected"})


class Availability(models.Model):
    """
    A Flavor that is enabled for a specific user.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(ClientUser, on_delete=models.CASCADE)
    flavor = models.ForeignKey(Flavor, on_delete=models.CASCADE)
    is_enabled = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{}.{}".format(self.flavor, self.user)

    class Meta:
        verbose_name_plural = "Availabilities"

ablator/web_admin/forms/AvailabilitySearchForm.py
from django import forms


class SearchForm(forms.Form):
    user_identity_string = forms.CharField()

ablator/web_admin/views/availability.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import FormView, ListView, UpdateView, DeleteView

from core.models import Availability, ClientUser
from web_admin.forms.AvailabilitySearchForm import SearchForm


@method_decorator(login_required, name="dispatch")
class AvailabilitySearch(FormView):
    template_name = "core/availability/search.html"
    form_class = SearchForm

    def form_valid(self, form):
        user_key = form.cleaned_data["user_identity_string"]
        return HttpResponseRedirect(reverse_lazy("availability-list", kwargs={"user": user_key}))


@method_decorator(login_required, name="dispatch")
class AvailabilityList(ListView):
    template_name = "core/availability/list.html"

    def get_queryset(self):
        client_user = ClientUser.user_from_object(self.kwargs["user"], organization=self.request.user.ablatoruser.organization)
        return Availability.objects.filter(flavor__functionality__app__organization=self.request.user.ablatoruser.organization).filter(
            user=client_user
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_identifier"] = self.kwargs["user"]
        return context


@method_decorator(login_required, name="dispatch")
class AvailabilityUpdate(UpdateView):
    template_name = "core/availability/update.html"
    fields = [
        "flavor",
        "is_enabled",
    ]

    def get_success_url(self):
        return reverse_lazy("availability-list", kwargs={"user": self.kwargs["user"]})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_identifier"] = self.kwargs["user"]
        return context

    def get_queryset(self):
        return Availability.objects.filter(flavor__functionality__app__organization=self.request.user.ablatoruser.organization)


@method_decorator(login_required, name="dispatch")
class AvailabilityDelete(DeleteView):
    template_name = "core/availability/confirm_delete.html"

    def get_success_url(self):
        return reverse_lazy("availability-list", kwargs={"user": self.kwargs["user"]})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_identifier"] = self.kwargs["user"]
        return context

    def get_queryset(self):
        return Availability.objects.filter(flavor__functionality__app__organization=self.request.user.ablatoruser.organization)

ablator/web_admin/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Ablator</title>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style type="text/css">
        body {
            background: linear-gradient(170deg, white, white 30%, lightgray);
            min-height: 100vh;
            padding-bottom: 8rem;
        }

        /* Custom page footer */
        .footer {
            padding: 1.5rem 0 0.5rem;
            margin-top: 2rem;
            font-size: small;
            color: #ccc;
            background: radial-gradient(100% 100% at 50% 100%, #000 0%, #000000 99%, rgba(0, 0, 0, 0) 100%);

            position: fixed;
            width: 100%;
            bottom: 0;
        }

        .footer a {
            color: #fff;
        }

        /* Quick and dirty nested navbars*/
        li.nav-item ul.nav {
            margin-left: 1em;
            margin-bottom: 1em;
        }

        /* Scrollable Code Blocks */
        .pre-x-scrollable {
            overflow: auto;
            -ms-word-wrap: normal;
            word-wrap: normal;
            overflow-wrap: normal;
            white-space: pre;
        }

        .subinline, .subinline div {
            display: inline-block;
        }
    </style>

</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <a class="navbar-brand" href="{% url 'home' %}">{{ request.user.ablatoruser.organization.name }} ablator</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% if app %}{{ app.name }}{% else %}Apps{% endif %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for app in request.user.ablatoruser.organization.app_set.all %}
                            <a class="dropdown-item" href="{% url 'app-detail' app.id %}">{{ app.name }}</a>
                        {% endfor %}
                    </div>
                </li>

                {% if app %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if functionality %}{{ functionality.name }}{% else %}Functionalities{% endif %}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            {% for functionality in app.functionality_set.all %}
                                <a class="dropdown-item"
                                   href="{% url 'functionality-detail' functionality.id %}">{{ functionality.name }}</a>
                            {% endfor %}
                        </div>
                    </li>
                {% endif %}

                {% if request.user.is_authenticated %}
                    <li class="nav-item {% block tags_nav_active %}{% endblock %}">
                        <a href="{% url 'tags-list' %}" class="nav-link">Tags</a>
                    </li>
                    <li class="nav-item {% block availability_nav_active %}{% endblock %}">
                        <a href="{% url 'availability-index' %}" class="nav-link">Client Users</a>
                    </li>
                {% endif %}
            </ul>

            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}

                    <li class="nav-item {% block users_profile_active %}{% endblock %}">
                        <a class="nav-link" href="{% url 'profile-detail' request.user.id %}">{{ request.user }}</a>
                    </li>
                    <li class="nav-item {% block users_nav_active %}{% endblock %}">
                        <a class="nav-link" href="{% url 'user-list' %}">
                            {{ request.user.ablatoruser.organization.name }}
                        </a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'logout' %}">Sign Out</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

{% block body %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message|safe }}
                </div>
            {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
    </div>
{% endblock %}


<footer class="footer">
    <div style="max-width: 30rem; margin-left: auto; margin-right: auto;">
        <img src="{% static 'ablator/ablator_logo_white.png' %}" alt="The ablator logo, a space
            capsule screaming through the atmosphere" width="50px"
             style="float: left; margin-right: 20px">

        <p>
            Ablator Version <kbd>{{ request.ablator_version }}</kbd>
            Distributed under the BSD License. <br>See <a
                href="http://ablator.io/">ablator.io</a> for more info
        </p>
    </div>
</footer>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

<script src="{% static "ablator/main.js" %}"></script>

{% block scripts %}{% endblock %}
</body>
</html>

ablator/web_admin/templates/app.html
{% extends '_base.html' %}
{% block back %}
    <li class="breadcrumb-item active">{{ app.name }}</li>
{% endblock %}

{% block content %}
    <h1>{{ app.name }}</h1>
    <hr>

    <div class="row">
        {% for functionality in app.functionality_set.all %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title"><a
                                href="{% url 'functionality' functionality.id %}">{{ functionality.name }}</a>
                        </h4>
                        <div class="progress">
                            {% for flavor in functionality.flavor_set.all %}
                                <div class="progress-bar"
                                     style="width: {{ flavor.width_percent }}%; background-image: none; background-color: #{{ flavor.color }}">
                                </div>
                            {% endfor %}
                        </div>
                        <hr>

                        <div class="row">
                            <div class="col">
                                <div class="text-center">
                                <span class="display-2">{{ functionality.number_of_enabled_users }}</span><br>
                                <small>users enabled</small>
                            </div>
                            </div>
                            <div class="col">
                                <div class="text-center">
                                    <span class="display-2">{{ functionality.number_of_users }}</span><br>
                                    <small>potential users</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {% if forloop.counter|divisibleby:2 %}
                </div>
                <br>
                <div class="row">
            {% endif %}
        {% endfor %}
        <div class="col-md-6">
            <div class="card text-center">
                    <div class="card-body">
                        <button type="button" class="btn btn-outline-primary">Add New App
                        </button>
                    </div>
                </div>
        </div>
        </div>

{% endblock %}

ablator/web_admin/templates/index.html
{% extends '_base.html' %}
{% load static %}
{% block home_nav_active %}active{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-6">
        {% for app in apps %}
        <div class="card mb-4">
            <div class="card-body">
                <h2 class="card-title"><a href="{% url 'app-detail' app.id %}">{{ app.name }}</a>
                </h2>
                {% for functionality in app.functionality_set.all %}
                {% if functionality.rollout_strategy == 'enable_globally' %}
                <div class="progress" style="border-radius: 0;">
                    <div class="progress-bar"
                         style="height: 5px; width: 100%; background-image: none; background-color: #28a745">
                    </div>
                </div>
                {% elif functionality.rollout_strategy == 'recall' %}
                <div class="progress" style="border-radius: 0;">
                    <div class="progress-bar"
                         style="height: 5px; width: 100%; background-image: none; background-color: #dc3545">
                    </div>
                </div>
                {% else %}
                <div class="progress" style="border-radius: 0;">
                    {% for flavor in functionality.flavor_set.all %}
                    <div class="progress-bar"
                         style="height: 5px; width: {{ flavor.width_percent }}%; background-image: none; background-color: #{{ flavor.color }}">
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>

        {% empty %}
            <h1 style="margin-top: 8rem;">Welcome to Ablator</h1>
            <p class="lead">Ablator manages Features.</p>
            <p>
                These features are grouped into Apps. To get started, create your first app now.
            </p>
        {% endfor %}
        <a class="btn btn-lg btn-primary btn-block" href="{% url 'app-create' %}" role="button">Create a
                new App</a>
    </div>
    <div class="col-md-6 text-center">
        <img src="{% static 'ablator/ablator_logo.svg' %}" alt="The ablator logo, a space
            capsule screaming through the atmosphere" width="100%">
    </div>
</div>

{% endblock %}